import type { CourseDetailsWithProgress } from '@/entities/course/course'

export const MOCK_MY_COURSE_DETAIL: CourseDetailsWithProgress = {
    id: '1',
    title: 'Blockchain',
    slug: 'blockchain',
    snippet: 'Learn professional web design from scratch with industry-standard tools and techniques',
    description: 'Lorem ipsum dolor sit amet consectetur aenean in ornare hendrerit ac interdum ac sit etiam commodo euismod ultrices maecenas commodo amet ornare vel lacus vel et non lobortis ullamcorper quis interdum.\n\nLorem ipsum dolor sit amet consectetur aenean in ornare hendrerit ac interdum ac sit etiam commodo euismod ultrices maecenas commodo amet ornare vel lacus vel et non lobortis ullamcorper quis interdum.',
    previewVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    coverUrl: '/src/assets/webflow/images/blockchain-image-courselify-x-webflow-template.jpg',
    status: 'PUBLISHED',
    discordInviteUrl: 'https://discord.gg/example',
    units: [
        {
            id: '1',
            courseId: '1',
            title: 'Start',
            snippet: 'Lorem ipsum dolor amet consectetur pellentesque scelerisque fermentum.',
            description: 'Introduction to web design fundamentals',
            iconUrl: '/src/assets/webflow/images/start-course-icon-courselify-webflow-ecommerce-template.png',
            orderIndex: 1,
            isPublished: true,
            createdAt: '2024-01-01T00:00:00Z',
            updatedAt: '2024-01-01T00:00:00Z',
            lessons: [],
            totalLessons: 10,
            completedLessons: 10,
            progressPercentage: 100.0
        },
        {
            id: '2',
            courseId: '1',
            title: 'Typography',
            snippet: 'Lorem ipsum dolor amet consectetur pellentesque scelerisque fermentum.',
            description: 'Master the art of typography in web design',
            iconUrl: '/src/assets/webflow/images/typography-course-icon-courselify-webflow-ecommerce-template.png',
            orderIndex: 2,
            isPublished: true,
            createdAt: '2024-01-01T00:00:00Z',
            updatedAt: '2024-01-01T00:00:00Z',
            lessons: [],
            totalLessons: 12,
            completedLessons: 7,
            progressPercentage: 58.33
        },
        {
            id: '3',
            courseId: '1',
            title: 'Layout',
            snippet: 'Lorem ipsum dolor amet consectetur pellentesque scelerisque fermentum.',
            description: 'Learn composition and balance in layouts',
            iconUrl: '/src/assets/webflow/images/layout-course-icon-courselify-webflow-ecommerce-template.png',
            orderIndex: 3,
            isPublished: true,
            createdAt: '2024-01-01T00:00:00Z',
            updatedAt: '2024-01-01T00:00:00Z',
            lessons: [],
            totalLessons: 8,
            completedLessons: 0,
            progressPercentage: 0.0
        },
        {
            id: '4',
            courseId: '1',
            title: 'Color',
            snippet: 'Lorem ipsum dolor amet consectetur pellentesque scelerisque fermentum.',
            description: 'Understanding color relationships and emotions',
            iconUrl: '/src/assets/webflow/images/color-course-icon-courselify-webflow-ecommerce-template.png',
            orderIndex: 4,
            isPublished: true,
            createdAt: '2024-01-01T00:00:00Z',
            updatedAt: '2024-01-01T00:00:00Z',
            lessons: [],
            totalLessons: 12,
            completedLessons: 0,
            progressPercentage: 0.0
        },
        {
            id: '5',
            courseId: '1',
            title: 'Imagery',
            snippet: 'Lorem ipsum dolor amet consectetur pellentesque scelerisque fermentum.',
            description: 'Working with images in web design',
            iconUrl: '/src/assets/webflow/images/imagery-course-icon-courselify-webflow-ecommerce-template.png',
            orderIndex: 5,
            isPublished: true,
            createdAt: '2024-01-01T00:00:00Z',
            updatedAt: '2024-01-01T00:00:00Z',
            lessons: [],
            totalLessons: 8,
            completedLessons: 0,
            progressPercentage: 0.0
        },
        {
            id: '6',
            courseId: '1',
            title: 'UI Elements',
            snippet: 'Lorem ipsum dolor amet consectetur pellentesque scelerisque fermentum.',
            description: 'Creating intuitive user interfaces',
            iconUrl: '/src/assets/webflow/images/ui-elements-course-icon-courselify-webflow-ecommerce-template.png',
            orderIndex: 6,
            isPublished: true,
            createdAt: '2024-01-01T00:00:00Z',
            updatedAt: '2024-01-01T00:00:00Z',
            lessons: [],
            totalLessons: 12,
            completedLessons: 0,
            progressPercentage: 0.0
        }
    ]
}